USE employees;
INSERT INTO department (name) VALUE ('Human Resources'),
('Finance'),
('IT'),
('Sales'),
('Marketing'),
('Research and Development'),
('Operations');

INSERT INTO role (title, salary, department_id) VALUE ('HR Manager', 60000, 1),
('HR Specialist', 45000, 1),
('Accountant', 50000, 2),
('Financial Analyst', 55000, 2),
('IT Manager', 65000, 3),
('Software Developer', 70000, 3),
('Sales Manager', 60000, 4),
('Sales Representative', 50000, 4),
('Marketing Manager', 60000, 5),
('Marketing Specialist', 45000, 5),
('R&D Manager', 70000, 6),
('R&D Scientist', 65000, 6),
('Operations Manager', 60000, 7),
('Logistics Coordinator', 45000, 7),
('Production Supervisor', 50000, 7);


INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUE ('John', 'Doe', 1, NULL),
('Jane', 'Smith', 2, 1),
('Alice', 'Johnson', 2, 1),
('Bob', 'Williams', 3, NULL),
('Charlie', 'Brown', 3, 4),
('Eve', 'Davis', 3, 4),
('Frank', 'Martinez', 4, NULL),
('Grace', 'Garcia', 4, 7),
('Hank', 'Miller', 4, 7),
('Ivy', 'Wilson', 5, NULL),
('Jack', 'Moore', 5, 10),
('Kate', 'Taylor', 5, 10),
('Leo', 'Anderson', 6, NULL),
('Mia', 'Thomas', 6, 13),
('Noah', 'Jackson', 6, 13),
('Olivia', 'White', 7, NULL),
('Parker', 'Harris', 7, 16),
('Quincy', 'Martin', 7, 16),
('Rebecca', 'Thompson', 8, NULL),
('Sam', 'Gonzalez', 8, 19),
('Tina', 'Clark', 8, 19),
('Uma', 'Lopez', 9, NULL),
('Victor', 'Lee', 9, 22),
('Wendy', 'Lewis', 9, 22),
('Xander', 'Young', 10, NULL),
('Yasmin', 'Hernandez', 10, 25),
('Zane', 'Hall', 10, 25),
('Aria', 'King', 11, NULL),
('Ben', 'Wright', 11, 28),
('Carla', 'Murphy', 11, 28),
('Danny', 'Robinson', 12, NULL);


